config/routes.rb
Rails.application.routes.draw do
  root "sales#index"

  resources :sales, only: [:index] do
    collection do
      post :import
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :merchant, class_name: "Person"

  has_many :sales
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :addresses
  has_many :items, class_name: "Item", foreign_key: "merchant_id"
  has_many :sales, class_name: "Sale", foreign_key: "purchaser_id"
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :item
  belongs_to :purchaser, class_name: "Person"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
include ActionView::Helpers::NumberHelper

class SalesController < ApplicationController
  def index
    @total = ::Sales::CalculateTotalService.call
    @sales = Sale.all
    @sales = @sales.paginate(:page => params[:page], :per_page => 10)
  end

  def import    
    @import = ::Sales::ImportService.(params[:file])
    
    if @import[:success]
      redirect_to sales_path, notice: "Sales was successfully imported. Total gross income: #{number_to_currency(@import[:value])}"
    else
      redirect_to sales_path, flash: { error: @import[:value] }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type.to_sym
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Nuuvemchallenge</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/shared/header' %>
    <main role="main">
      <%= render partial: 'layouts/shared/intro' %>
      <%= render partial: 'layouts/shared/flash_messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/shared/_header.html.erb
<header>
  <div class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <span><%= image_tag("nuuvem.svg", size: "30") %></span> 
        <strong> Nuuvem - Challenge</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/shared/_intro.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>You are in Nuuvem</h1>
    <p class="lead text-muted">Your digital store and gaming platform for Windows, macOS, and Linux. With Nuuvem you will discover, buy and manage your games.</p>
  </div>
</section>

app/views/sales/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= form_with(url: import_sales_path, method: :post, multipart: true, class: "form-inline") do %>
      <div class="form-group mb-2">
        <%= label_tag "file", "Sale file:" %>
        <%= file_field_tag :file, class: "form-control-file" %>
      </div>

      <%= submit_tag "Import", class: "btn btn-primary mb-2" %>
    <% end %>
  </div>
</div>

<div class="container">
  <hr />
  <div class="page-header">
      <div class="float-left">
        <h2>Sales</h2>
      </div>
      <div class="float-right">
        <h5 class="text-right">Total: <%= number_to_currency(@total) %></h5>
      </div>
      <div class="clearfix"></div>
  </div>

  
  <div class="row">
    <% if @sales.blank? %>
      <hr />
      <div>
        <p>There are no registered sales.</p>
      </div>
    <% else %>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Purchaser Name</th>
            <th scope="col">Item Description</th>
            <th scope="col">Item Price</th>
            <th scope="col">Merchant Address</th>
            <th scope="col">Merchant Name</th>
          </tr>
        </thead>
        <tbody>
          <% @sales.each do |sale| %>
            <tr>
              <td><%= sale.purchaser.name %></td>
              <td><%= sale.item.description %></td>
              <td><%= number_to_currency(sale.item.price) %></td>
              <td><%= "#{sale.item&.merchant&.addresses&.first&.number} #{sale.item&.merchant&.addresses&.first&.street}" %></td>
              <td><%= sale.item&.merchant&.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="pages">
        <%= will_paginate @sales, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    <% end %>
  </div>
</div>